### ISSUE TITLE
Realm Listener Events

### ISSUE THREAD

**Issue by samtoya** [artis-auxilium/realm-orm#6]
How do you add listeners for when an object is created?

**Comment by d3v2a** [comment]
you can add listener when you open database which return a promise that will be resolved with the Realm instance when it's available.

```js
realm.open().then((realmInstance) => {
  realmInstance.addListener('change', listener);
})

```

or you can do it on collection too (see [Collection Notification](https://realm.io/docs/javascript/latest#collection-notifications) )

```js
collectionListenerRetainer = Dog.all();
collectionListenerRetainer.addListener(listener);
```

**Comment by samtoya** [comment]
Thanks a million. It works!!
